[tool.ruff]
line-length = 125
ignore = ["D203"]
[tool.black]
line-length = 125
target-version = ['py310']
extend-exclude = '''
(
  ^/migrations\/
)
'''
[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']
